### ISSUE TITLE
Plot figure.3 (a)(b)

### ISSUE THREAD

**Issue by jingzhengli** [XLearning-SCU/2021-CVPR-MvCLN#1]
Thanks for the nice code. What tool can be used to draw the heat map such as figure 3 (a) and (b) in your paper?

**Comment by mouxingyang** [comment]
Thanks for your interest. The figure could be plotted with the help of the following snippet.

ax = fig.gca(projection='3d')
ax.plot_surface()

**Comment by jingzhengli** [comment]
> 

Got it, thanks
